### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by adaddeo** [spree-contrib/spree_related_products#109]
Thoughts on having relations touch the relatable when they are updated?

I can submit a PR.

**Comment by futhr** [comment]
+1 I normally do that always because its like any other data attribute, so go for it!

**Comment by michaelmichael** [comment]
I normally have to manually invoke `Rails.cache.clear` in the production console to get related products to show up. Would this proposed PR solve that?

**Comment by adaddeo** [comment]
@michaelmichael yes

I submitted the PR

**Comment by adaddeo** [comment]
@michaelmichael yes

I submitted the PR: #112
