### ISSUE TITLE
DEPRECATION WARNING: Passing an argument to force an association Rails 5.1

### ISSUE THREAD

**Issue by jcsena** [spree-contrib/spree_related_products#139]
_DEPRECATION WARNING: Passing an argument to force an association to reload is now deprecated and will be removed in Rails 5.1. Please call `reload` on the result collection proxy instead. (called from irb_binding at (irb):15)_

`product.relations(rt)
`

**Comment by florianjosefreheis** [comment]
Came across the same issue. Any news how to solve this?
