### ISSUE TITLE
NoMethodError (undefined method `type' for nil:NilClass)

### ISSUE THREAD

**Issue by matissg** [spree-contrib/spree_related_products#169]
I'm triying to Add Related Product 
(`http://localhost:3000/admin/products/apache-baseball-jersey/related`), however I get this error:
```
NoMethodError in Spree::Api::V1::VariantsController#index

undefined method `type' for nil:NilClass
Extracted source (around line #28):

#26             raise "No table named #{table} exists."
#27           end
*28           attr.klass.columns.find { |column| column.name == name }.type
#29         end
#30 
#31         def evaluate(search, opts = {})

Extracted source (around line #35):

#33           return ransacker.type
#34         else
*35           context.type_for(self)
#36         end
#37       end
#38 

Extracted source (around line #260):

#258 
#259       def default_type
*260         predicate.type || (attributes.first && attributes.first.type)
#261       end
#262 
#263       def inspect
```
I've created related product type "Accessories" and I have default Spree seeded product catalog in my demo Spree store.

Versions I have:

- Rails: 5.2.2
- Ruby: 2.5.1
- Spree: 3.6.6
- gem 'spree_related_products', github: 'spree-contrib/spree_related_products'

Any ideas if behavior above is due to my versions or that is some error?

**Comment by GabAlexandria** [comment]
@matissg For you and anyone else that encounters this issue, this is a workaround i'm using. This problem seems to be related to associations, possibly because of a still [open bug](https://github.com/activerecord-hackery/ransack/issues/756). The app I'm basing this on is using `spree 3.5.0` and `ransack 1.8.8`.

In Spree, this line [here]( https://github.com/spree/spree/blob/master/core/app/models/spree/variant.rb#L104) lists simply `product` as an association, which seems to cause the variants [query](https://github.com/spree/spree/blob/master/backend/app/assets/javascripts/spree/backend/variant_autocomplete.js#L39) to fail with the above error when `product_name_or_sku_cont` is passed to `ransack`. To get around it, in a decorator I have overwritten

`self.whitelisted_ransackable_associations = %w[option_values product prices default_price]`
to
`self.whitelisted_ransackable_associations = %w[option_values product_name prices default_price]`

and that got everything working for now.

**Comment by matissg** [comment]
@GabAlexandria  Thank you, looks like your suggested workaround is working.

**Comment by theunraveler** [comment]
This suggestion silences the error, but does not appear to filter the results at all. In my initial digging, the reason it seems to fail is that `Spree::Product.columns` does not seem to include the `name` column on that model. The column is in my `schema.rb`, but not included in that method's return value. That's what ultimately causing `default_type` in ransack to fail.

Is anyone else able to confirm that? If so, it seems like it might a bigger issue than spree or ransack.

In the meantime, I did the following as a more complete workaround that both silences the error and also filters the results:

```ruby
Spree::Variant.class_eval do
  self.whitelisted_ransackable_associations = %w(option_values prices default_price)
  self.whitelisted_ransackable_scopes = %i(product_name_or_sku_cont)

  def self.product_name_or_sku_cont(q)
    joins(:product)
      .where('spree_products.name ILIKE :q OR sku ILIKE :q', q: q)
  end
end
```

**Comment by aivils** [comment]
Confirmed!
Seems, this unwanted side effect of spree_globalize.
spree 3.3.6, ransack 1.8.10, spree_globalize master, globalize 5.2.0

```
2.3.8 :015 > Spree::Product.columns.map(&:name)
 => ["id", "available_on", "discontinue_on", "deleted_at", "tax_category_id", "shipping_category_id", "created_at", "updated_at", "promotionable", "status"] 
2.3.8 :016 > Spree::Product.translated_attribute_names
 => [:name, :description, :meta_title, :meta_description, :meta_keywords, :slug] 
2.3.8 :017 > Spree::Product.ignored_columns
 => ["name", "description", "meta_title", "meta_description", "meta_keywords", "slug"] 
2.3.8 :018 > 
```

ransack works fine
```
2.3.8 :019 > Spree::Variant.ransack(sku_cont: '---')
 => Ransack::Search<class: Spree::Variant, base: Grouping <conditions: [Condition <attributes: ["sku"], predicate: cont, values: ["---"]>], combinator: and>> 
2.3.8 :020 >
```

product_name does not work
```
2.3.8 :018 > Spree::Variant.ransack(product_name_or_sku_cont: '---')
NoMethodError: undefined method `type' for nil:NilClass
        from (irb):18
```

**Comment by RaimundSchramm** [comment]
Hi folks,

I have not understood the internals yet...but building upon the solution from theunraveler above - which didnt work for me - i managed to make something work as it seems (but maybe it's still wrong or not good)

```ruby
Spree::Variant.class_eval do
  self.whitelisted_ransackable_associations = %w(option_values prices default_price)
  self.whitelisted_ransackable_scopes = %i(product_name_or_sku_cont)

  def self.product_name_or_sku_cont(q)
    where(product_id: by_product_name(q).ids)
    .or(Spree::Variant.where('sku LIKE :q', q: "%#{q}%"))
  end

  def self.by_product_name(q)
    Spree::Product.joins(:translations)
      .where('spree_product_translations.name LIKE :q', q: "%#{q}%")
  end
end
```

theunraveler 's scope didn't work for me, so i tried until i finally found a scope that can select a Variant based on the value of the Name-Attribute of the Translations-Association of the Product it belongs to

**Comment by flobby** [comment]
Sorry to spread bad news but it still fails for me with the exact same error message.

I'm on latest spree (6e8b53bfaa5a8bc5fb8b27cb61ae89dc1c150b5c) and spree_related_products (e2a64fbfcde045ba94f541a405f6523a0d03c802).

Can someone confirm this fix actually resolved the issue without any other changes?

How did I test? Just tried to access this:
http://localhost:3000/api/v1/variants?q%5Bproduct_name_or_sku_cont%5D=klebefolie&token=...

And also tried to search in admin for related products fails.

**Comment by aplegatt** [comment]
@flobby This issue should be fixed with PRs: https://github.com/spree/spree/pull/10255 and https://github.com/spree/spree/pull/10252. Could You update Spree version and check if it still occurs?

**Comment by isasi88** [comment]
Hi, any updates on this? Just had the same error when installing Globalize Gem.
Is there any fix?
