### ISSUE TITLE
`require': cannot load such file -- sass/rails (LoadError)

### ISSUE THREAD

**Issue by staycreativedesign** [spree-contrib/spree_related_products#192]
There is a dependency on having sass/rails , since sassc is the newest version of sass/rails.  Just remove 

```require 'sass/rails'``` inside lib/spree_related_products.rb

And it will fix this error

```require': cannot load such file -- sass/rails (LoadError)```

**Comment by damianlegawiec** [comment]
Fixed :)

**Comment by staycreativedesign** [comment]
hehehe :)
