### ISSUE TITLE
Update for spree 2.4

### ISSUE THREAD

**Issue by chriscarpenter12** [spree-contrib/spree_related_products#99]
Is there going to be a stable branch update for spree 2.4? Looking to upgrade, but not sure if 2.3 or master should be used for spree 2.4.

**Comment by futhr** [comment]
Hi, there is one now that I created from `2-3-stable` when I started to rework `master` branch for Spree v.3.0.0.beta. Specs still failing on `2-4-stable` but you welcome to test it out.
